#!/bin/bash

# Set your personal data here:
rssfile="rss.xml"
blogfile="blog.htm"
stylesheet="\/styles\/style.css"
author="No Soy Anónimo"
website="https://nosoyanonimo.github.io/"
dir=$(pwd)

getHelp() { \
	echo -e "This system will take the blog entries you write and add them into the RSS file and HTML file of your choosing. Set which files to use by editing the 'lb' file directly and changing the variables at the top.\n"
	echo -e "To fully prepare these files, add the following line to both files where you want the content to be added:\n"
	echo -e "<!-- LB -->\n"
	echo -e "Usage: 'new': create new draft; 'finalize': finish draft and add it to the RSS and HTML page; 'delete': delete a finished page.\n"
	echo -e "As you finalize posts, they will be appended in the appropriate format below that line.\n"
	echo -e "Blog posts will be stored in 'blog/' and drafts will be in 'blog/.drafts/'. To delete drafts, you only need delete their .html files directly, but use the 'lb delete' command to remove finalized posts since they appear in three places."
}

listandReturn() { \
	#echo "Listing contents of $1."
	echo "Enlistando los contenidos de $1."
	ls $1 | nl
	#read -p "Pick an entry by number to $2, or press ctrl-c to cancel. " number
	read -p "Escoja una entrada por número para $2, o pulse ctrl-c para cancelar. " number
	chosen=$(basename $(ls $1 | nl | grep -w  "$number" | awk '{print $2}'))
	}

getTitle() { \
	#echo "Post will be stored as draft in $dir/blog/.drafts until finalized."
	echo "El post se almacenará como borrador en $dir/blog/.drafts hasta que sea finalizado"
	read -p "Escriba un título para su publicación: " title
	url=$(echo $title | sed -e "s/'\|\"\|=\|+\|_\|,\|:\|;\|?\|!\|@\|\*\|&\|(\|)\|[\|]\|<\|>//g;s/ /-/g" | tr '[:upper:]' '[:lower:]') ;}

postNew() { \
	mkdir -p $dir/blog/.drafts
	echo -e "<h2 id='$url'>$title</h2><small>[<a aria-hidden=\"true\" href=\"$blogfile#$url\">Enlace</a>&mdash;<a href=\"blog/$url.html\">Ir al post</a>]</small>\n\n<++>" >> $dir/blog/.drafts/$url.html && vim $dir/blog/.drafts/$url.html ;}

finalize() { \
	listandReturn $dir/blog/.drafts finalizar
	url=$(cat $dir/blog/.drafts/$chosen | grep -o "<h2 id='\(.\)*'>" | cut -d "'" -f2)
	title=$(cat $dir/blog/.drafts/$chosen | grep -o "<h2 id='\(.\)*h2>" |sed -e 's/<[^>]*>//g')
	echo "AddDescription \"$title\" $chosen" >> $dir/blog/.htaccess
	rssdate=$(date '+%a, %d %b %Y %H:%M:%S %z')
	webdate=$(date '+%a, %d %b %Y %H:%M:%S %z')
	tmpdir=$(mktemp -d)
	echo -e "\n<item>\n<title>$title</title>\n<guid>$website$blogfile#$url</guid>\n<pubDate>$rssdate</pubDate>\n<description><![CDATA[\n$(cat $dir/blog/.drafts/$chosen)\n]]></description>\n</item>\n"> $tmpdir/rss.xml
	echo -e "\n<article>\n$(cat $dir/blog/.drafts/$chosen)\n<small>$webdate <b>por </b> $author</small>\n</article>\n" > $tmpdir/html.html
	sed -i "/<!-- LB -->/r $tmpdir/html.html" $blogfile
	sed -i "/<!-- LB -->/r $tmpdir/rss.xml" $rssfile
	header="<html>\n<head>\n<title>$title<\/title>\n<link rel='stylesheet' type='text\/css' href='$stylesheet'>\n<meta charset='utf-8'\/>\n<\/head>\n<body>"
	footer="<\/body>\n<footer>por <strong>$author<\/strong><\/footer>\n<\/html>"
	sed  "s/href=\"/href=\"..\//g;s/\.\.\/http/http/g;0,/^/s//$header/;0,/<h2 id=/s//<h1 id=/;0,/h2>/s//h1>/;\$a$footer" $dir/blog/.drafts/$chosen > $dir/blog/$chosen
	rm $dir/blog/.drafts/$chosen
}

delete() { \
	listandReturn "$dir/blog/*.html" eliminar
	base=$(echo $chosen | cut -f1 -d'.')
	read -p "¿En verdad desea eliminar \"$base\"? (s,N) " choice
	[[ $choice =~ [Ss] ]] || exit
	#rm $dir/blog/$chosen && echo "Blog post deleted from directories."
	rm $dir/blog/$chosen && echo "La entrada del blog fue eliminada de los directorios"
	#sed -i "/<item/{:a;N;/<\/item>/!ba};/$base/d" $rssfile && echo "Entry removed from RSS feed file."
	sed -i "/<item/{:a;N;/<\/item>/!ba};/$base/d" $rssfile && echo "La entrada fue eliminada del archivo RSS"
	#sed -i "/<article/{:a;N;/<\/article>/!ba};/$base/d" $blogfile && echo "HTML code removed from blogfile."
	sed -i "/<article/{:a;N;/<\/article>/!ba};/$base/d" $blogfile && echo "Código HTML eliminado del archivo del blog."
	}

case "$1" in
	new) getTitle && postNew ;;
	finalize) finalize ;;
	delete) delete ;;
	*) getHelp ;;
esac
